# Generated by Django 3.2.6 on 2023-08-03 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='User_permission',
        ),
        migrations.AlterField(
            model_name='authorized',
            name='Authorized',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Authorized',
            field=models.ForeignKey(limit_choices_to=['admin', 'company', 'customer'], on_delete=django.db.models.deletion.CASCADE, related_name='User', to='practice.authorized'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Email',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_Password',
            field=models.TextField(max_length=100),
        ),
    ]
