# Generated by Django 3.2.6 on 2023-08-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_auto_20230803_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='User_Authorized',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='practice.authorized'),
        ),
    ]
