# Generated by Django 3.2.6 on 2023-08-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_user_user_authorized'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserName',
            new_name='User_Name',
        ),
    ]
